### ISSUE TITLE
Update in ReadMe

### ISSUE THREAD

**Issue by zatch3301** [zatch3301/Game-of-Life#2]
Feel free to contribute ^^

**Comment by aaronzshey** [comment]
I can help!  I'll add instructions on building from source and actually playing the game haha.
How do I make the pull request?  It just redirects me to some place to compare branches.
Hm ok, it seems like the owner has to make a branch.  Could you make a new branch called "ReadmeUpdateBranch" for me to pull and work with?

**Comment by hauze-v** [comment]
@CarlyRaeJepsenStan Hey, if @zatch3301 doesn't make a new branch for you, you can also "fork" the repo by using the button in the far top-right corner of the screen when viewing the project.

This essentially copies the repo onto your profile where you can make changes and then create a pull request off of that.

Send me a message if you have any more questions!

**Comment by aaronzshey** [comment]
@hauze-v thanks!  I'm trying some stuff right now.
If I clone it, and then I try to push my changes, what happens?
Hm ok, I just tried that and I got a 403 error - I'll fork it right now and paste the link to my fork in this comment. 
[Fork](https://github.com/CarlyRaeJepsenStan/Game-of-Life)

I might also make something that shows the number of generations that have passed...

**Comment by hauze-v** [comment]
Nice. Yeah so now that you have a fork, simply make your changes against that repository, and then when you're ready to open a pull request against Zatch's master branch you can do so by clicking the pull request button underneath the "Add File" button located to the left of the green "Code" button.

**Comment by aaronzshey** [comment]
This should probably be closed as my PR was accepted 👍
